parser: "@typescript-eslint/parser"

plugins:
  - "@typescipt-eslint"

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"

env:
  node: true

parserOptions:
  project:
    - "packages/*"
